TFKUBE-343: Fixed the synchrony url update for Confluence when domain is not provided.
atlassian-labs/data-center-terraform pull request #167
Opened 2022-02-22 05:12 UTC by nghazali

2022-02-22 23:32 UTC, yzha645 approved these changes

2022-02-22 23:32 UTC, yzha645 commented on config.tfvars
> +# By default, Bitbucket will use the version defined in the helm chart. If you wish to override the version, uncomment
```suggestion
# By default, Bitbucket will use the version defined in the Helm chart. If you wish to override the version, uncomment
```

2022-02-22 23:35 UTC, yzha645 commented on config.tfvars
> +# the following line and set the bitbucket_software_version to any of the versions available on https://hub.docker.com/r/atlassian/bitbucket/tags
```suggestion
# the following line and set the bitbucket_version_tag to any of the versions available on https://hub.docker.com/r/atlassian/bitbucket/tags
```

2022-02-22 23:38 UTC, yzha645 commented
The same typo within the comments apply to the other two PRs for Confluence and Bamboo.

2022-02-22 23:40 UTC, yzha645 requested changes
The same typo within the comments apply to the other two PRs for Confluence and Bamboo.

2022-02-23 03:27 UTC, yzha645 approved these changes

2022-02-23 03:57 UTC, errcode1202 approved these changes

2022-02-23 03:57 UTC, errcode1202 commented on config.tfvars
> +#bitbucket_version_tag = "<BITBUCKET_VERSION_TAG>"
```suggestion
# By default, Bitbucket will use the version defined in the Bitbucket Helm chart: 
# https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/bitbucket/Chart.yaml 
# If you wish to override the version, uncomment the following line and set the bitbucket_version_tag to any of the # versions published for Bitbucket on Docker Hub: https://hub.docker.com/r/atlassian/bitbucket/tags
#bitbucket_version_tag = "<BITBUCKET_VERSION_TAG>"
```

2022-02-23 04:09 UTC, nanux approved these changes
Pending conflict resolution

2022-02-23 04:17 UTC, merged