TFKUBE-441: Compromise tagging failure in installer during e2e tests.
atlassian-labs/data-center-terraform pull request #214
Opened 2022-04-25 23:26 UTC by nghazali

## Pull request description

Compromise tagging failure in installer during e2e tests

## Checklist
- [ ] I have successful end to end tests run (with & without domain)
- [ ] I have added unit tests (if applicable)
- [ ] I have user documentation (if applicable)

2022-04-26 01:18 UTC, nanux requested changes

2022-04-26 01:18 UTC, nanux commented on install.sh
> +  if [ $_ == 0 ]; then
```suggestion
  if [ $? == 0 ]; then
```
I haven't really used `$_` but from reading https://unix.stackexchange.com/questions/280453/understand-the-meaning-of that is not what we want to do here. I think we need to check the exit code.

2022-04-26 01:18 UTC, nanux commented on install.sh
> +    log "Resource tags are applied to ASG and all EC2 instances."
```suggestion
    log "Resource tags were applied to ASG and all EC2 instances."
```

2022-04-26 01:18 UTC, nanux commented on install.sh
> +    log "Resource tags are not applied to ASG and all EC2 instances." "ERROR"
```suggestion
    log "Resource tags were not applied to ASG and all EC2 instances." "ERROR"
```

2022-04-26 01:18 UTC, nanux commented on install.sh
> +    log "The script is executed by end2end test. Tagging of ASG and EC2 resources failure will be compromised."
```suggestion
    log "The script is executed by end2end test. Failure in tagging of ASG and EC2 resources will not cause the script to error out."
```

2022-04-26 01:19 UTC, nanux commented
Why do we have failures in the EC2 tagging?

2022-04-26 01:31 UTC, nanux commented
> One use case of failure in tagging was version mismatch which is not applying to e2e test. Normally we don't have problem in tagging - but as part of our investigation we observed at least one case of e2e test failed that the reason was tagging module. As we didn't find similar error in out tests, so I think is not worth to spend more time for this issue and this code will prevent e2e test failure in future.

I see. Is there a possibility that this might mask a problem with our tagging code?

2022-04-26 04:54 UTC, nghazali commented
> > One use case of failure in tagging was version mismatch which is not applying to e2e test. Normally we don't have problem in tagging - but as part of our investigation we observed at least one case of e2e test failed that the reason was tagging module. As we didn't find similar error in out tests, so I think is not worth to spend more time for this issue and this code will prevent e2e test failure in future.
> 
> I see. Is there a possibility that this might mask a problem with our tagging code?

No, this will apply only in e2e test. (Only when install is executed with FORCE_FLAG. This is off by default and is an internal flag and is not documented for vendor or any other purposed use.)

2022-04-27 04:52 UTC, nanux commented
> > > One use case of failure in tagging was version mismatch which is not applying to e2e test. Normally we don't have problem in tagging - but as part of our investigation we observed at least one case of e2e test failed that the reason was tagging module. As we didn't find similar error in out tests, so I think is not worth to spend more time for this issue and this code will prevent e2e test failure in future.
> > 
> > 
> > I see. Is there a possibility that this might mask a problem with our tagging code?
> 
> No, this will apply only in e2e test. (Only when install is executed with FORCE_FLAG. This is off by default and is an internal flag and is not documented for vendor or any other purposed use.)

I understand it is only for tagging. But if the tagging will become broken, the end to end test won't really show that failure.

2022-04-27 04:52 UTC, nanux approved these changes

2022-04-27 16:21 UTC, nghazali commented
I see your point @nanux and is a valid one. Let's discuss if it worth we merge this PR or we get more benefit of drop it.

2022-04-27 23:50 UTC, nghazali commented
Regarding the team decision I close this without merge.

2022-04-27 23:50 UTC, closed without merging