TFKUBE-454: Restore EBS snapshot from index recovery file
atlassian-labs/data-center-terraform pull request #224
Opened 2022-05-03 05:47 UTC by nghazali

## Pull request description

Restore EBS snapshot from index recovery file with no need to full re-index. The snapshots for RDS and EBS should be match and EBS snapshot should contain index recovery files. 
Also user should pass the date of EBS snapshot creation. This will be used to calculate the age of the snapshot to extend the lifecycle to avoid out of date error (by default the max valid age of snapshot is 2 days). 

## Checklist
- [ ] I have successful end to end tests run (with & without domain)
- [ ] I have added unit tests (if applicable)
- [ ] I have user documentation (if applicable)

2022-05-03 05:48 UTC, nghazali commented
TODO: Documentation for the introduced variable (`confluence_shared_home_snapshot_creation_date`)

2022-05-04 07:28 UTC, nanux requested changes
I don't think the additional complexity and configurability are bringing a lot of customer value. We need to just convince Confluence that it should recover any index it finds in the shared home. Ideally if we would have some `confluence.validate.index.snapshot.timestamp = false` property. Unfortunatelly we don't have that so I think setting the value to some very high number as we are doing https://github.com/atlassian-labs/data-center-terraform/pull/223 is sufficient and easier to maintain.

2022-05-04 07:28 UTC, nanux commented on modules/products/confluence/locals.tf
> +        "-Dreindex.thread.count=${local.number_of_threads}",
I think we can keep these properties if they are generally improving indexing.

2022-05-04 07:28 UTC, nanux commented on modules/products/confluence/locals.tf
> +  number_of_threads = min(4, floor(tonumber(local.confluence_software_resources.cpu)))
This assumes we always get an integer (not `2500m` for example). The `confluence_cpu` is defined as a `string` type so it is possible to pass it in a different format. We can potentially make it more explicit, convert it here or at least document it.

2022-05-04 07:28 UTC, nanux commented on modules/products/confluence/locals.tf
> +        "-Dconfluence.cluster.index.recovery.generation.timeout=480", # seconds
We can keep these properties, maybe extracting the `480` values into `locals.tf` to give them some documentation and sensible variable names.

2022-05-17 00:14 UTC, yzha645 commented
As long as all of `main`, `change` and `edge` index are in place and in sync with the records in database, Confluence will be recovered from index snapshot stored in shared home. The age of snapshot is not a problem here, since index recovery is not actually checking it during startup.

In terms of the three properties regarding reindex thread counts, they either already have the default value 4, or already doing some calculation to dynamically decide the value based on workload and available cpus. Seems like we're re-enforcing Confluence features. https://confluence.atlassian.com/conf713/recognized-system-properties-1077914597.html 

Will close this PR for now, we can re-visit it later on if necessary.

2022-05-17 00:14 UTC, closed without merging