Update support wording
atlassian-labs/data-center-terraform pull request #289
Opened 2022-11-28 22:31 UTC by errcode1202

Minor updates

## Pull request description

_Provide description for the PR_

## Checklist
- [NA] I have successful end to end tests run (with & without domain)
- [NA] I have added unit tests (if applicable) 
- [X] I have user documentation (if applicable)

2022-11-28 22:32 UTC, bianchi2 approved these changes

2022-11-28 22:43 UTC, nanux requested changes

2022-11-28 22:43 UTC, nanux commented on docs/docs/README.md
> -!!! warning "Officially support warning"
We should update https://github.com/atlassian-labs/data-center-terraform/blob/ff1a0f6136ced65e62fe38bae3fccc06f3027c5c/docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md?plain=1#L4 as well.

2022-11-29 06:12 UTC, nghazali approved these changes

2022-11-30 22:58 UTC, nanux approved these changes

2022-11-30 23:15 UTC, merged