TFKUBE-109: default tags
atlassian-labs/data-center-terraform pull request #52
Opened 2021-11-23 23:14 UTC by jjeongatl

Default tags added on aws providers
remove all resource tags but we can still add any extra tags on leaf module level

2021-11-30 22:55 UTC, jjeongatl commented
I created asg_ec2_tagging module for workaround. The module will be initialised only when infra is ready. It uses output of the terraform result to fetch ASG and EC2 information.

2021-12-01 04:42 UTC, nghazali requested changes

2021-12-01 04:42 UTC, nghazali commented on pkg/scripts/uninstall.sh
> +}
Move this stuff into `cleanup.sh`

2021-12-01 04:42 UTC, nghazali commented on pkg/scripts/uninstall.sh
> +  cd "${SCRIPT_PATH}/../modules/AWS/asg_ec2_tagging"
If you change the current folder you need to make sure you back to the same folder when you done with cleaning. I mean your script should not change the current folder before the script.

2021-12-01 04:42 UTC, nghazali commented on pkg/scripts/install.sh
> +  terraform "${CHDIR}" apply -auto-approve "-var-file=${CONFIG_FILE}" -var s3_bucket="${S3_BUCKET}" -var bucket_key="${BUCKET_KEY}/terraform.tfstate"  -compact-warnings
```suggestion
  ASG_EC2_TAG_DIR="${SCRIPT_PATH}/../modules/AWS/asg_ec2_tagging"
  cp "${SCRIPT_PATH}/../../${CONFIG_FILE}" "${ASG_EC2_TAG_DIR}"

  terraform -chdir="${ASG_EC2_TAG_DIR}" init
  terraform -chdir="${ASG_EC2_TAG_DIR}" apply -auto-approve "${OVERRIDE_CONFIG_FILE}" -var s3_bucket="${S3_BUCKET}" -var bucket_key="${BUCKET_KEY}/terraform.tfstate"  -compact-warnings
```

2021-12-01 23:17 UTC, nghazali approved these changes

2021-12-02 06:25 UTC, nanux approved these changes

2021-12-02 06:26 UTC, merged